version: '3.7'

services:
  mongo:
    image: mongo:4.4.1-bionic
    env_file: .envdb
    volumes:
      - ./mongodb:/data/db
    networks:
      - app-network

  bot:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    volumes:
      - ./sounds:/app/sounds
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge