version: '3.1'

services:
  mongo:
    image: mongo:4.2.7
    env_file: .envdb
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 127.0.0.1:27017:27017

  bot:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    volumes:
      - ./data:/srv/app
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge